### ISSUE TITLE
escaped characters not handled correctly in strings

### ISSUE THREAD

**Issue by Conduitry** [Rich-Harris/golden-fleece#6]
If some json5 contains a string containing an escaped newline, in the parsed or evaluated version, that newline will be lost.

```javascript
fleece.evaluate('"\\n"')
```

This returns an empty string. This also happens with strings containing `\r` or `\t` or `\\`.

Strings containing `\x##` or `\u####` escape characters are also not handled correctly. The `\x` or `\u` is dropped and in the evaluated string the `##` or `####` is left as-is.

**Comment by Conduitry** [comment]
Ugh. I'm an idiot. That _was_ an actual newline character in the string. 🤦‍♂️ 

There's still something going on here, editing the issue...

**Comment by Conduitry** [comment]
It looks like the issue is that other escaped characters are not properly handled [here](https://github.com/Rich-Harris/golden-fleece/blob/2c5ef5a5fc52b098a49e29ba07ffcae4c9b77425/src/parse.ts#L343).

**Comment by Conduitry** [comment]
Patching of strings so that they contain newlines is also problematic, as the newlines are simply copied into the patched string without escaping them.

**Comment by Rich-Harris** [comment]
Thanks — it looks like the bug is in `fleece.parse` — working on a fix

**Comment by Conduitry** [comment]
It looks like that fix won't handle the `\x##` and `\u####` cases - and it also doesn't look like it would handle the issue in `patch`.

**Comment by Conduitry** [comment]
Also I'm not 100% clear on what should be done with unknown escape sequences. With this change, golden-fleece will completely drop things like `\q` from strings. The normal js parser would treat that as simply `q` and the json parser would throw an error. I don't know what the json5 specs say about this.

**Comment by Rich-Harris** [comment]
Ah yep, `\x` and `\u` still need handling. Shouldn't have closed this. `\q` is handled though — if it's not one of the escapeable characters (`\t`, `\b`, `\n` and so on) it just adds the character to the result.

**Comment by Conduitry** [comment]
Oh whoops I missed the `value += escapeable[char] || char;`.

I'm a bit more concerned about the `patch`/`stringify` issue though actually. In https://github.com/sveltejs/svelte.technology/issues/262 if you make any edits to the text area, it corrupts the json5 data by having actual newlines in the string.

**Comment by Rich-Harris** [comment]
Opened https://github.com/Rich-Harris/golden-fleece/pull/12. Those characters won't get escaped upon stringification, but *maybe* that's okay?

**Comment by Conduitry** [comment]
I think that's good enough for now. If we run into issues or if it surfaces that this isn't json5-compliant, we can revisit - but for now that's definitely better than what there was before.

**Comment by Conduitry** [comment]
Actually the list of characters that json5 officially escapes was [pretty easy to find](https://github.com/json5/json5/blob/master/src/stringify.js#L110). It might make sense to augment the list I added in #10 to include the couple of extra ones.

**Comment by Rich-Harris** [comment]
I *think* all the various cases are handled now (thanks!) — you think we're good to close this?

**Comment by Conduitry** [comment]
Yup I think everything should be covered now.
